version: '3'

services:

  auth-service-postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_service
    volumes:
      - ./auth-service-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  song-service-postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=song_service
    volumes:
      - ./song-service-postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  statistics-service-mongo:
    image: mongo:7.0.2-jammy
    volumes:
      - ./statistics-service-mongo-data:/data/db
    ports:
      - "27018:27017"
    restart: unless-stopped

  message-broker:
    image: rabbitmq:3.12.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"

  discovery-server:
    image: mabocontainer/songs-ms-discovery-server:1.0
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"

  api-gateway:
    image: mabocontainer/songs-ms-api-gateway:1.0
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  auth-service:
    image: mabocontainer/songs-ms-auth-service:1.0
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-service-postgres
      - discovery-server
      - api-gateway

  song-service:
    image: mabocontainer/songs-ms-song-service:1.0
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - song-service-postgres
      - message-broker
      - discovery-server
      - api-gateway
      - auth-service

  statistics-service:
    image: mabocontainer/songs-ms-statistics-service:1.0
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - statistics-service-mongo
      - message-broker
      - discovery-server
      - api-gateway
